import eslintReact from '@eslint-react/eslint-plugin';
import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import prettier from 'eslint-config-prettier/flat';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/** @type {import('eslint').Linter.Config[]} */
export default [
    ...defineConfig(
        {
            ignores: [
                'vendor',
                'node_modules',
                'public',
                'bootstrap/ssr',
                'tailwind.config.js',
                'resources/js/**/*.js',
            ],
        },
        {
            files: [
                'resources/js/**/*.ts',
                'resources/js/**/*.tsx',
                'src/**/*.ts',
                'src/**/*.tsx',
            ],
            extends: [
                js.configs.recommended,
                tseslint.configs.recommended,
                eslintReact.configs['recommended-typescript'],
            ],
            languageOptions: {
                globals: {
                    ...globals.browser,
                    ...globals.node,
                },
                parser: tseslint.parser,
                parserOptions: {
                    projectService: true,
                    tsconfigRootDir: import.meta.dirname,
                },
            },
            rules: {
                '@typescript-eslint/strict-boolean-expressions': 'error',
                '@typescript-eslint/no-explicit-any': 'error',
                '@typescript-eslint/member-ordering': 'error',

                // Keep the migration low-noise. These rules are valuable in
                // greenfield React 19 codebases, but would require broad refactors here.
                '@eslint-react/no-array-index-key': 'off',
                '@eslint-react/no-forward-ref': 'off',
                '@eslint-react/no-use-context': 'off',
                '@eslint-react/no-context-provider': 'off',
                '@eslint-react/no-unnecessary-use-prefix': 'off',
                '@eslint-react/purity': 'off',
                '@eslint-react/use-state': 'off',
                '@eslint-react/naming-convention/ref-name': 'off',

                // Keep existing effects low-noise while migrating eslint-react rules.
                '@eslint-react/set-state-in-effect': 'off',
            },
        },
        {
            files: ['resources/js/wayfinder/index.ts'],
            rules: {
                // Generated by @laravel/vite-plugin-wayfinder; keep lint stable without
                // fighting the generator output.
                '@typescript-eslint/strict-boolean-expressions': 'off',
            },
        },
        prettier,
    ),
];
