import type { SanitizedHtml } from '#app/lib/safe-html';
import { cn } from '#app/lib/utils';
import type { ElementType } from 'react';
import { createElement } from 'react';

type SafeHtmlProps = {
    html: SanitizedHtml;
    as?: ElementType;
    className?: string;
    // Any other props for the chosen element/component
    [key: string]: unknown;
};

export function SafeHtml({ html, as, className, ...rest }: SafeHtmlProps) {
    const Tag: ElementType = as ?? 'div';

    // HTML is expected to be sanitized server-side (e.g. HTMLPurifier) or generated by the app (e.g. QR SVG).
    // Centralizing this keeps the surface area of raw HTML rendering small and auditable.
    // eslint-disable-next-line @eslint-react/dom/no-dangerously-set-innerhtml
    return createElement(Tag, {
        ...rest,
        className: cn(className),
        dangerouslySetInnerHTML: { __html: html },
    });
}
